/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2019-05-08 05:11:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import xjtucad.SSOManager;

public final class userLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("xjtucad.SSOManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;\r\ncharset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");

    SSOManager ssoManager = SSOManager.getInstance();
    String formPostUrl="";
    String tokenSyncUrl="";
    if(ssoManager.getMode()==SSOManager.CLIENT_MODE){
        formPostUrl=ssoManager.getSsoLoginUrl();
        tokenSyncUrl=ssoManager.getSsoLoginUrl();
    }
    String referer = request.getParameter("serviceURL");
    if(referer==null) {
        referer = request.getHeader("referer");
    }
    if(referer==null){
        referer=request.getRequestURL().toString();
    };
    String error = request.getParameter("error");

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>创新方法工作平台统一登录</title>\r\n");
      out.write("    <meta name=\"description\" content=\"User login page\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("    <!-- bootstrap & fontawesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/webresources/ace-master/assets/css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/webresources/ace-master/assets/font-awesome/4.5.0/css/font-awesome.min.css\"\r\n");
      out.write("          type=\"text/css\">\r\n");
      out.write("    <!-- text fonts -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/webresources/ace-master/assets/css/fonts.googleapis.com.css\" type=\"text/css\">\r\n");
      out.write("    <!-- ace styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/webresources/ace-master/assets/css/ace.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/webresources/ace-master/assets/css/ace-rtl.min.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/webresources/ace-master/assets/css/ace-skins.min.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"login-layout light-login\">\r\n");
      out.write("<!-- /.main-container -->\r\n");
      out.write("<!-- basic scripts -->\r\n");
      out.write("<div class=\"main-container\">\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-10 col-sm-offset-1\">\r\n");
      out.write("                <div class=\"login-container\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"center\">\r\n");
      out.write("                        <h1>\r\n");
      out.write("                            <i class=\"ace-icon fa fa-leaf green\"></i>\r\n");
      out.write("                            <span class=\"red\">创新方法平台</span>\r\n");
      out.write("                            <span class=\"white\" id=\"id-text2\">用户登录</span>\r\n");
      out.write("                        </h1>\r\n");
      out.write("                        <h4 class=\"blue\" id=\"id-company-text\">© 西安交通大学CAD/CAM研究室</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"space-6\"></div>\r\n");
      out.write("                    <div class=\"position-relative\">\r\n");
      out.write("                        <div id=\"login-box\" class=\"login-box widget-box no-border visible\">\r\n");
      out.write("                            <div class=\"widget-body\">\r\n");
      out.write("                                <div class=\"widget-main\">\r\n");
      out.write("                                    <h4 class=\"header blue lighter bigger\">\r\n");
      out.write("                                        <i class=\"ace-icon fa fa-coffee green\"></i>\r\n");
      out.write("                                        请输入账号信息\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    ");

                                        if(error!=null){
                                            out.print("<div class=\"alert alert-danger\">\n" +
                                                    "<button type=\"button\" class=\"close\" data-dismiss=\"alert\">\n" +
                                                    "<i class=\"ace-icon fa fa-times\"></i>\n" +
                                                    "</button>\n" +
                                                    "<strong>\n" +
                                                    "<i class=\"ace-icon fa fa-times\"></i>\n" +
                                                    "登录异常\n" +
                                                    "</strong>\n" +
                                                    error +
                                                    "<br>\n" +
                                                    "</div>");
                                        }
                                    
      out.write("\r\n");
      out.write("                                    <div class=\"space-6\"></div>\r\n");
      out.write("                                    <form id=\"loginForm\" method=\"post\" action=\"");
      out.print(formPostUrl);
      out.write("/webresources/user/login\">\r\n");
      out.write("                                        <fieldset>\r\n");
      out.write("                                            <label class=\"block clearfix\">\r\n");
      out.write("                                                                    <span class=\"block input-icon input-icon-right\">\r\n");
      out.write("                                                                        <input id=\"username\" name=\"username\" type=\"text\"\r\n");
      out.write("                                                                               class=\"form-control\" placeholder=\"用户名\">\r\n");
      out.write("                                                                        <i class=\"ace-icon fa fa-user\"></i>\r\n");
      out.write("                                                                    </span>\r\n");
      out.write("                                            </label>\r\n");
      out.write("                                            <label class=\"block clearfix\">\r\n");
      out.write("                                                                    <span class=\"block input-icon input-icon-right\">\r\n");
      out.write("                                                                        <input id=\"password\" name=\"password\"\r\n");
      out.write("                                                                               type=\"password\" class=\"form-control\"\r\n");
      out.write("                                                                               placeholder=\"密码\">\r\n");
      out.write("                                                                        <i class=\"ace-icon fa fa-lock\"></i>\r\n");
      out.write("                                                                    </span>\r\n");
      out.write("                                            </label>\r\n");
      out.write("                                            <div style=\"display: none\">\r\n");
      out.write("                                                <label class=\"block clearfix \">\r\n");
      out.write("                                                                        <span class=\"block input-icon input-icon-right\">\r\n");
      out.write("                                                                            <input id=\"serviceURL\" name=\"serviceURL\"\r\n");
      out.write("                                                                                   type=\"text\" class=\"form-control\"\r\n");
      out.write("                                                                                   value=\"");
      out.print(referer);
      out.write("\">\r\n");
      out.write("                                                                        </span>\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"space\"></div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"clearfix\" style=\"text-align: center\">\r\n");
      out.write("                                                <button type=\"submit\" class=\"width-35 btn btn-sm btn-primary\">\r\n");
      out.write("                                                    <i class=\"ace-icon fa fa-key\"></i>\r\n");
      out.write("                                                    <span class=\"bigger-110\">登录</span>\r\n");
      out.write("                                                </button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </fieldset>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.widget-main -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.widget-body -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"userBox\" class=\"login-box widget-box no-border \">\r\n");
      out.write("                            <div class=\"widget-body\">\r\n");
      out.write("                                <div class=\"widget-main\">\r\n");
      out.write("                                    <h4 class=\"header blue lighter bigger\">\r\n");
      out.write("                                        <i class=\"ace-icon fa fa-coffee green\"></i>\r\n");
      out.write("                                        当前已登录账号\r\n");
      out.write("                                    </h4>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"space-6\"></div>\r\n");
      out.write("                                    <div class=\"scroll-content\" style=\"max-height: 200px;\">\r\n");
      out.write("                                        <div class=\"profile-activity clearfix\">\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <img class=\"pull-left\" alt=\"Alex Doe's avatar\"\r\n");
      out.write("                                                     src=\"/webresources/ace-master/assets/images/avatars/avatar4.png\">\r\n");
      out.write("                                                <label>用户名：</label>\r\n");
      out.write("                                                <a class=\"user\" id=\"usernamebox\" href=\"#\">111</a>\r\n");
      out.write("                                                <div class=\"time\">\r\n");
      out.write("                                                    <i class=\"ace-icon fa fa-clock-o bigger-110\"></i>\r\n");
      out.write("                                                    已登录\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.widget-main -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"toolbar clearfix\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <a onclick=\"logout()\" class=\"forgot-password-link\">\r\n");
      out.write("                                            <i class=\"ace-icon fa fa-arrow-left\"></i>\r\n");
      out.write("                                            退出当前用户\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <a id=\"serviceURL2\" href=\"");
      out.print(referer);
      out.write("\" class=\"user-signup-link\">\r\n");
      out.write("                                            使用当前用户继续访问\r\n");
      out.write("                                            <i class=\"ace-icon fa fa-arrow-right\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.widget-body -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.position-relative -->\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.col -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.main-content -->\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"/webresources/ace-master/assets/js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("<script> $(function () {\r\n");
      out.write("    if (!haseToken()) {\r\n");
      out.write("        getToken();\r\n");
      out.write("    } else {\r\n");
      out.write("        getUserInfo();\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function haseToken() {\r\n");
      out.write("    var cookies = document.cookie.split(';');\r\n");
      out.write("    var is = false;\r\n");
      out.write("    cookies.forEach(cookie => {\r\n");
      out.write("        if (cookie.split('=')[0] === \"AU_TOKEN\") {\r\n");
      out.write("            is = true;\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("    return is;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getUserInfo() {\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: '/webresources/user/login',\r\n");
      out.write("        type: 'get',\r\n");
      out.write("        success: function (data) {\r\n");
      out.write("            if (data.state !== undefined && !data.state) {\r\n");
      out.write("                //如果返回空，说明未登录\r\n");
      out.write("                $(\"#login-box\").addClass(\"visible\");\r\n");
      out.write("                $(\"#userBox\").removeClass(\"visible\");\r\n");
      out.write("            } else {\r\n");
      out.write("                //如果返回字符串，说明返回的是用户名\r\n");
      out.write("                $(\"#usernamebox\").html(data.content);\r\n");
      out.write("                $(\"#userBox\").addClass(\"visible\");\r\n");
      out.write("                $(\"#login-box\").removeClass(\"visible\");\r\n");
      out.write("                $(\"#forgot-box\").removeClass(\"visible\");\r\n");
      out.write("                $(\"#signup-box\").removeClass(\"visible\");\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function logout() {\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: '/webresources/user/logout',\r\n");
      out.write("        type: 'get',\r\n");
      out.write("        success: function (data) {\r\n");
      out.write("            location.reload();\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("}</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
